=== BrokenToast/2122-LMSG_LuisPA/U4/dtd10.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT prediccion (municipios)>
    <!ATTLIST prediccion xmlns:xsi CDATA #IMPLIED
        xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
<!ELEMENT municipios (dias)>
<!ELEMENT dias (prob_precipitacion,estado_cielo,viento,temperatura)>
    <!ATTLIST dias fecha CDATA #REQUIRED>
<!ELEMENT prob_precipitacion (#PCDATA)>
<!ELEMENT estado_cielo (#PCDATA)>
    <!ATTLIST estado_cielo descripcion CDATA #REQUIRED>
<!ELEMENT viento (direccion,velocidad)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT velocidad (#PCDATA)>
<!ELEMENT temperatura (maxima,minima)>
<!ELEMENT maxima (#PCDATA)>
<!ELEMENT minima (#PCDATA)>

=== BrokenToast/2122-LMSG_LuisPA/U4/E1/UD4-XML10-Luis_PA/xml10.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->

<!DOCTYPE prediccion SYSTEM "dtd10.dtd">

<prediccion xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='schema10.xsd'>
    <municipios>
        <dias fecha="2022-02-09">
            <prob_precipitacion>10</prob_precipitacion>
            <estado_cielo descripcion="Cielos despejado">50</estado_cielo>
            <viento>
                <direccion>Norte</direccion>
                <velocidad>40</velocidad>
            </viento>
            <temperatura>
                <maxima>17</maxima>
                <minima>-3</minima>
            </temperatura>
        </dias>
    </municipios>
</prediccion>
