=== BrokenToast/2122-LMSG_LuisPA/U4/schema05.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="company">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="employee" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="firstName"/>
                            <xs:element name="LastName"/>
                            <xs:element name="ContactNo"/>
                            <xs:element name="Email"/>
                            <xs:element name="Address">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="City"/>
                                        <xs:element name="State"/>
                                        <xs:element name="Zip"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== BrokenToast/2122-LMSG_LuisPA/U4/XML5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->
<company xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='schema05.xsd'>
    <employee>
        <firstName>Juan</firstName>
        <LastName>Sanchez</LastName>
        <ContactNo>123456789</ContactNo>
        <Email>juansanchez@company.com</Email>
        <Address>
            <City>Bangalore</City>
            <State>Karnataka</State>
            <Zip>560212</Zip>
        </Address>
    </employee>
</company>
