=== BrokenToast/2122-LMSG_LuisPA/U4/schema03.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="history">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="descripcion" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name"/>
                            <xs:element name="fecha">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="dia"/>
                                        <xs:element name="mes"/>
                                        <xs:element name="aÃ±o"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== BrokenToast/2122-LMSG_LuisPA/U4/XML03.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
<!DOCTYPE history[
    <!ELEMENT history (descripcion*)>
    <!ELEMENT descripcion (name,fecha)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT fecha (dia,mes,año)>
    <!ELEMENT dia (#PCDATA)>
    <!ELEMENT mes (#PCDATA)>
    <!ELEMENT año (#PCDATA)>
    
]>
-->
<history xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='schema03.xsd'>
    <descripcion>
        <name>Youtube</name>
        <fecha>
            <dia>15</dia>
            <mes>2</mes>
            <año>2005</año>
        </fecha>
    </descripcion>
    <descripcion>
        <name>Google</name>
        <fecha>
            <dia>4</dia>
            <mes>9</mes>
            <año>1998</año>
        </fecha>
    </descripcion>
    <descripcion>
        <name>facebook</name>
        <fecha>
            <dia>4</dia>
            <mes>2</mes>
            <año>2004</año>
        </fecha>
    </descripcion>  
</history>
