=== BrokenToast/2122-LMSG_LuisPA/U4/schema01.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="email">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="remitente" type="xs:string"/>
                <xs:element name="destinatario">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="fecha" type="xs:date"/>
                <xs:element name="asunto" type="xs:string"/>
                <xs:element name="mensaje" type="xs:string" minOccurs="0"/>
                <xs:element name="fichero" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                            <xs:attribute name="type" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== BrokenToast/2122-LMSG_LuisPA/U4/E1/XML01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE email[
    <!ELEMENT email (remitente , destinatario , fecha , asunto , mensaje , fichero*)>
    <!ATTLIST email xmlns:xsi CDATA #IMPLIED
                             xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
    <!ELEMENT remitente (#PCDATA)>
    <!ELEMENT destinatario (nombre+)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT fecha (#PCDATA)>
    <!ELEMENT asunto (#PCDATA)>
    <!ELEMENT mensaje (#PCDATA)>
    <!ELEMENT fichero (#PCDATA)>
    <!ATTLIST fichero type CDATA #REQUIRED>
]>
<email xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='schema01.xsd'>
    <remitente>luis.perast@edcua.jcyl.es</remitente>
    <destinatario>
        <nombre>erpepe@gmail.com</nombre>
        <nombre>apa@gmail.com</nombre>
        <nombre>manuel@hotmail.com</nombre>
    </destinatario>
    <fecha>2022-01-20</fecha>
    <asunto>Multa</asunto>
    <mensaje>
        Deven pagar una multa de 300â‚¬ mas inpuestos.
    </mensaje>
    <fichero type="application/pdf">
        multa.pdf
    </fichero>
    <fichero type="application/pdf">
        inpuestos.pdf
    </fichero>
</email>
