=== BrokenToast/2122-LMSG_LuisPA/U4/schema04.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="curricu">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" type="xs:string"/>
                <xs:element name="apellidos" type="xs:string"/>
                <xs:element name="year" type="xs:gYear"/>
                <xs:element name="residencia">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ciudad" type="xs:string"/>
                            <xs:element name="pais" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="datos ">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="telefonos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="movil" maxOccurs="unbounded">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[0-9]{3}[0-9]{3}[0-9]{3}"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="fijo" maxOccurs="unbounded">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[0-9]{3}[0-9]{3}[0-9]{3}"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="email" maxOccurs="unbounded"/>
                           <xs:element name="perfil" type="xs:string"/>
                           <xs:element name="descripcion" type="xs:string"/>
                           <xs:element name="competencias">
                              <xs:complexType>
                                  <xs:sequence>
                                      <xs:element name="competencia" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute name="nombre" type="xs:string"/>
                                                <xs:attribute name="nivel" default="medio">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="bajo"/>
                                                            <xs:enumeration value="medio"/>
                                                            <xs:enumeration value="alto"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                   </xs:sequence>
                               </xs:complexType>
                           </xs:element>
                           <xs:element name="formaciones">
                              <xs:complexType>
                                  <xs:sequence>
                                      <xs:element name="formacion" maxOccurs="unbounded">
                                          <xs:complexType>
                                            <xs:attribute name="nombre" type="xs:string"/>
                                            <xs:attribute name="centro" type="xs:string"/>
                                            <xs:attribute name="year" type="xs:string"/>  
                                        </xs:complexType>       
                                    </xs:element>
                                   </xs:sequence>
                               </xs:complexType>
                           </xs:element>
                           <xs:element name="experiencias">
                               <xs:complexType>
                                   <xs:sequence>
                                       <xs:element name="experiencia" maxOccurs="unbounded">
                                           <xs:complexType>
                                               <xs:sequence>
                                                   <xs:element name="puesto" type="xs:string"/>
                                                   <xs:element name="empresa" type="xs:string"/>
                                                   <xs:element name="año" type="xs:gYear"/>
                                                   <xs:element name="añofin" type="xs:gYear"/>
                                               </xs:sequence>
                                           </xs:complexType>
                                       </xs:element>
                                   </xs:sequence>
                               </xs:complexType>
                           </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== BrokenToast/2122-LMSG_LuisPA/U4/XML04.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
<!DOCTYPE curricu[
    <!ELEMENT curricu (nombre, apellidos, año,residencia,datos)>
    <!ATTLIST curricu xmlns:xsi CDATA #IMPLIED
                        xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellidos (#PCDATA)>
    <!ELEMENT año (#PCDATA)>
    <!ELEMENT residencia (ciudad,pais)>
    <!ELEMENT ciudad (#PCDATA)>
    <!ELEMENT pais (#PCDATA)>
    <!ELEMENT datos (telefonos,email*,perfil,descripcion,competencias?,formaciones?,experiencias?)>
    <!ELEMENT telefonos (movil*,fijo)>
    <!ELEMENT movil (#PCDATA)>
    <!ELEMENT fijo (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT perfil (#PCDATA)>
    <!ELEMENT descripcion (#PCDATA)>
    <!ELEMENT competencias (competencia+)>
    <!ELEMENT competencia EMPTY>
    <!ELEMENT nivel (#PCDATA)>
    <!ELEMENT formaciones (formacion+)>
    <!ELEMENT formacion EMPTY>
        <!ATTLIST formacion nombre CDATA #REQUIRED
                                    centro CDATA #REQUIRED
                                    year CDATA #REQUIRED >
    <!ELEMENT centro (#PCDATA)>
    <!ELEMENT experiencias (experiencia+)>
    <!ELEMENT experiencia (puesto,empresa,año,añofin?)>
    <!ELEMENT puesto (#PCDATA)>
    <!ELEMENT empresa (#PCDATA)>
    <!ELEMENT añofin (#PCDATA)>
    <!ATTLIST competencia nivel (bajo|medio|alto)  "medio"
                                         nombre CDATA #REQUIRED>
]>
-->
<curricu xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='schema04.xsd'>
    <nombre>Luis</nombre>
    <apellidos>Pérez Astorga</apellidos>
    <year>2002</year>
    <residencia>
        <ciudad>Benavente</ciudad>
        <pais>Reino de Leon</pais>
    </residencia>
    <datos>
        <telefonos>
            <movil>674770806</movil>
            <movil>789456123</movil>
            <fijo>978621453</fijo>
        </telefonos>
        <email>luis.perast@edcua.jcyl.es</email>
        <email>luispatb@gmail.com</email>
        <perfil>Luis Perez Astorga</perfil>
        <descripcion>Hola que tal </descripcion>
        <competencias>
            <competencia nombre="Organizado" nivel="alto"/>
            <competencia nombre="Pega Etiquetas" nivel="medio"/>
            <competencia nombre="Programacion Java" />
        </competencias>   
        <formaciones>
            <formacion nombre="Sistemas microinformaticos y redes" centro="IES Losa Sauces" year="2021"/>
            <formacion nombre="Desarroyo de aplicaciones web" centro="IES Losa Sauces" year="2023"/>
        </formaciones>
        <experiencias>
            <experiencia>
                <puesto>Administrador de Sistemas</puesto>
                <empresa>3dLac</empresa>
                <año>2021</año>
                <añofin>2021</añofin>
            </experiencia>
        </experiencias>     
    </datos>
</curricu>
